### ISSUE TITLE
Gligar evolution throws out a bunch of garbled mess

### ISSUE THREAD

**Issue by Khrisstias** [Blackout03/PixelWiki#1]
![2022-06-14_19 06 51](https://user-images.githubusercontent.com/37944220/173710152-000f9190-ecc1-4dee-ad1d-2e0958b55be5.png)

**Comment by Blackout03** [comment]
Okay. Will look into fixing this later today. Shouldn't be too hard.

**Comment by Blackout03** [comment]
https://www.curseforge.com/minecraft/mc-mods/pixelwiki/files/3847435

PixelWiki 1.0.1 should be reviewed soon. This issue has now been fixed. Some other changes as well.
